// FIXED TEMP SHIMS FOR HIGH-FREQUENCY BARREL/SDK IMPORTS
// Keep this while workspace snapshot is incomplete.

declare module '@app/payment-input' {
  export type CardinalResponse = any;
  export const CardinalResponse: any;
  export type PaymentInputInitMOffice = any;
  export const PaymentInputInitMOffice: any;
  export type PaymentInputSetupCompleteData = any;
  export const PaymentInputSetupCompleteData: any;
  export type PreviousScreenHandoverInformation = any;
  export const PreviousScreenHandoverInformation: any;
  export type RegisterCodeType = any;
  export const RegisterCodeType: any;
  export type SEARCH_METHOD_SELECTION = any;
  export const SEARCH_METHOD_SELECTION: any;
}

declare module '@app/payment-input/container' {
  export type PaymentInputCardInfo = any;
  export const PaymentInputCardInfo: any;
  export type PaymentInputContComponent = any;
  export const PaymentInputContComponent: any;
  export type PaymentInputScreenEntryInfo = any;
  export const PaymentInputScreenEntryInfo: any;
  export type dynamicSubject = any;
  export const dynamicSubject: any;
  export type screenEntryData = any;
  export const screenEntryData: any;
}

declare module '@app/payment-input/container/payment-input-cont.service' {
  export type PaymentInputContService = any;
  export const PaymentInputContService: any;
}

declare module '@app/payment-input/container/payment-input-cont.state' {
  export type AnaSkyCoinInfo = any;
  export const AnaSkyCoinInfo: any;
  export type PaymentInputCardHolderInfo = any;
  export const PaymentInputCardHolderInfo: any;
  export type PaymentInputCardInfo = any;
  export const PaymentInputCardInfo: any;
  export type PaymentInputInitMOffice = any;
  export const PaymentInputInitMOffice: any;
  export type PaymentInputScreenEntryInfo = any;
  export const PaymentInputScreenEntryInfo: any;
  export type initPhoneSelectData = any;
  export const initPhoneSelectData: any;
  export type screenEntryData = any;
  export const screenEntryData: any;
}

declare module '@common/helper' {
  export type BOTTOM_FLOAT_URLS = any;
  export const BOTTOM_FLOAT_URLS: any;
  export type BottomFloatUrlType = any;
  export const BottomFloatUrlType: any;
  export type CHANGE_CONTAINER_COLOR_URLS = any;
  export const CHANGE_CONTAINER_COLOR_URLS: any;
  export type DISABLED_WRAP_INNER_URLS = any;
  export const DISABLED_WRAP_INNER_URLS: any;
  export type apiEventAll = any;
  export const apiEventAll: any;
  export type checkAnaBizAndJapaneseOffice = any;
  export const checkAnaBizAndJapaneseOffice: any;
  export type checkFormEqual = any;
  export const checkFormEqual: any;
  export type checkFormGroupValidate = any;
  export const checkFormGroupValidate: any;
  export type checkFormListTouched = any;
  export const checkFormListTouched: any;
  export type checkFormListValidate = any;
  export const checkFormListValidate: any;
  export type createResponseName = any;
  export const createResponseName: any;
  export type deepCopy = any;
  export const deepCopy: any;
  export type deepCopyArray = any;
  export const deepCopyArray: any;
  export type defaultApiErrorEvent = any;
  export const defaultApiErrorEvent: any;
  export type defaultDispPassengerName = any;
  export const defaultDispPassengerName: any;
  export type deleteHtmlTags = any;
  export const deleteHtmlTags: any;
  export type fixedArrayCache = any;
  export const fixedArrayCache: any;
  export type formatSeconds = any;
  export const formatSeconds: any;
  export type getAgeOfSegmentDate = any;
  export const getAgeOfSegmentDate: any;
  export type getAirLineNameFromCache = any;
  export const getAirLineNameFromCache: any;
  export type getAirportNameFromCache = any;
  export const getAirportNameFromCache: any;
  export type getApiPhoneType = any;
  export const getApiPhoneType: any;
  export type getApplyDateCache = any;
  export const getApplyDateCache: any;
  export type getApplyListData = any;
  export const getApplyListData: any;
  export type getBoundFlightFromSegmentId = any;
  export const getBoundFlightFromSegmentId: any;
  export type getBoundFromBoundId = any;
  export const getBoundFromBoundId: any;
  export type getCabinClassNameKey = any;
  export const getCabinClassNameKey: any;
  export type getDisplayCart = any;
  export const getDisplayCart: any;
  export type getKeyListData = any;
  export const getKeyListData: any;
  export type getOwdRequestItinerariesFromCart = any;
  export const getOwdRequestItinerariesFromCart: any;
  export type getPassengerLabel = any;
  export const getPassengerLabel: any;
  export type getPassengerLabel2 = any;
  export const getPassengerLabel2: any;
  export type getPaxName = any;
  export const getPaxName: any;
  export type getPhoneCountryList = any;
  export const getPhoneCountryList: any;
  export type getTaxNameWithCountryCode = any;
  export const getTaxNameWithCountryCode: any;
  export type getTravelerFromTravelerId = any;
  export const getTravelerFromTravelerId: any;
  export type isCanada = any;
  export const isCanada: any;
  export type isEmptyObject = any;
  export const isEmptyObject: any;
  export type isStringEmpty = any;
  export const isStringEmpty: any;
  export type makeShareholderCoupons = any;
  export const makeShareholderCoupons: any;
  export type matchValidator = any;
  export const matchValidator: any;
  export type numberZeroUndefined = any;
  export const numberZeroUndefined: any;
  export type string8ToDate = any;
  export const string8ToDate: any;
  export type stringEmptyDefault = any;
  export const stringEmptyDefault: any;
  export type stringEmptyUndefined = any;
  export const stringEmptyUndefined: any;
  export type stringYMDHmsToDate = any;
  export const stringYMDHmsToDate: any;
  export type stringYMDToDate = any;
  export const stringYMDToDate: any;
  export type submitNavigate = any;
  export const submitNavigate: any;
  export type transform = any;
  export const transform: any;
  export type wheelchairBatteryApi = any;
  export const wheelchairBatteryApi: any;
  export type wheelchairBatteryValue = any;
  export const wheelchairBatteryValue: any;
}

declare module '@common/interfaces' {
  export type ANA_BIZ_OFFICE_CODE = any;
  export const ANA_BIZ_OFFICE_CODE: any;
  export type APF_OFFICE_CODE = any;
  export const APF_OFFICE_CODE: any;
  export type AddPassengerModalTravelerNum = any;
  export const AddPassengerModalTravelerNum: any;
  export type AirOfferUpgradeInfo = any;
  export const AirOfferUpgradeInfo: any;
  export type AirlineI18nJoinAll = any;
  export const AirlineI18nJoinAll: any;
  export type AirlineI18nJoinAllAirlineCodeData = any;
  export const AirlineI18nJoinAllAirlineCodeData: any;
  export type AirportAllData = any;
  export const AirportAllData: any;
  export type AnaBizLoginCookieType = any;
  export const AnaBizLoginCookieType: any;
  export type AnaBizLoginModel = any;
  export const AnaBizLoginModel: any;
  export type AnaBizLogoutModel = any;
  export const AnaBizLogoutModel: any;
  export type AncillarySvcType = any;
  export const AncillarySvcType: any;
  export type ApiErrorMap = any;
  export const ApiErrorMap: any;
  export type AswPageOutputUpsell = any;
  export const AswPageOutputUpsell: any;
  export type BoundFilterItem = any;
  export const BoundFilterItem: any;
  export type BoundUpgradeInfo = any;
  export const BoundUpgradeInfo: any;
  export type CabinClassUpgradeInfo = any;
  export const CabinClassUpgradeInfo: any;
  export type CabinClassUpgradeInfoList = any;
  export const CabinClassUpgradeInfoList: any;
  export type CalendarInfo = any;
  export const CalendarInfo: any;
  export type CancelAirOffer = any;
  export const CancelAirOffer: any;
  export type CartsUpdateTravelersRequestContactsDepartuteArrivalNotifications = any;
  export const CartsUpdateTravelersRequestContactsDepartuteArrivalNotifications: any;
  export type CartsUpdateTravelersRequestContactsSecondContact = any;
  export const CartsUpdateTravelersRequestContactsSecondContact: any;
  export type CartsUpdateTravelersRequestFrequentFlyerCards = any;
  export const CartsUpdateTravelersRequestFrequentFlyerCards: any;
  export type CartsUpdateTravelersRequestSupports = any;
  export const CartsUpdateTravelersRequestSupports: any;
  export type CartsUpdateTravelersRequestSupportsPregnant = any;
  export const CartsUpdateTravelersRequestSupportsPregnant: any;
  export type CartsUpdateTravelersRequestSupportsWalking = any;
  export const CartsUpdateTravelersRequestSupportsWalking: any;
  export type CartsUpdateTravelersRequestTravelerDisAbility = any;
  export const CartsUpdateTravelersRequestTravelerDisAbility: any;
  export type CartsUpdateTravelersRequestTravelerIslandCard = any;
  export const CartsUpdateTravelersRequestTravelerIslandCard: any;
  export type CartsUpdateTravelersRequestTravelersRequestParam = any;
  export const CartsUpdateTravelersRequestTravelersRequestParam: any;
  export type ChildSeatRequestInfo = any;
  export const ChildSeatRequestInfo: any;
  export type CodeFilterItem = any;
  export const CodeFilterItem: any;
  export type ComplexFlightAvailabilityStoreModel = any;
  export const ComplexFlightAvailabilityStoreModel: any;
  export type ContactRegState = any;
  export const ContactRegState: any;
  export type CountryCodeNameType = any;
  export const CountryCodeNameType: any;
  export type CriteoData = any;
  export const CriteoData: any;
  export type DEFAULT_CURRENCY_CODE_ASW = any;
  export const DEFAULT_CURRENCY_CODE_ASW: any;
  export type DeliveryInformationModel = any;
  export const DeliveryInformationModel: any;
  export type DeliveryInformationPaymentInformation = any;
  export const DeliveryInformationPaymentInformation: any;
  export type DisabilityType = any;
  export const DisabilityType: any;
  export type EmphType = any;
  export const EmphType: any;
  export type Emphed = any;
  export const Emphed: any;
  export type EquipmentI18nJoinPk = any;
  export const EquipmentI18nJoinPk: any;
  export type FFPriorityCodeByFFPriorityCode = any;
  export const FFPriorityCodeByFFPriorityCode: any;
  export type FareFullRuleData = any;
  export const FareFullRuleData: any;
  export type FareTypeData = any;
  export const FareTypeData: any;
  export type FareTypeItem = any;
  export const FareTypeItem: any;
  export type FareTypeOption = any;
  export const FareTypeOption: any;
  export type FilterConditionData = any;
  export const FilterConditionData: any;
  export type FilterConditionInput = any;
  export const FilterConditionInput: any;
  export type FilterConditionOutput = any;
  export const FilterConditionOutput: any;
  export type FilterItem = any;
  export const FilterItem: any;
  export type FlightType = any;
  export const FlightType: any;
  export type FlightUpgradeInfo = any;
  export const FlightUpgradeInfo: any;
  export type GetCompanyAccountsModel = any;
  export const GetCompanyAccountsModel: any;
  export type GoshokaiNetLoginDynamicParams = any;
  export const GoshokaiNetLoginDynamicParams: any;
  export type JAPANESE_REVENUE_OFFICE_CODE = any;
  export const JAPANESE_REVENUE_OFFICE_CODE: any;
  export type MAirport = any;
  export const MAirport: any;
  export type MCountry = any;
  export const MCountry: any;
  export type MCountryPos = any;
  export const MCountryPos: any;
  export type MCountryPosByContact = any;
  export const MCountryPosByContact: any;
  export type MLangCodeConvert = any;
  export const MLangCodeConvert: any;
  export type MListData = any;
  export const MListData: any;
  export type MMileageProgram = any;
  export const MMileageProgram: any;
  export type MPreorderMeal = any;
  export const MPreorderMeal: any;
  export type MServiceContentsI18N = any;
  export const MServiceContentsI18N: any;
  export type MSpecialMeal = any;
  export const MSpecialMeal: any;
  export type MealApplicationState = any;
  export const MealApplicationState: any;
  export type MealType = any;
  export const MealType: any;
  export type MyBookingServiceStoreModel = any;
  export const MyBookingServiceStoreModel: any;
  export type MyBookingStoreModel = any;
  export const MyBookingStoreModel: any;
  export type OFFICE_CODE_JP = any;
  export const OFFICE_CODE_JP: any;
  export type OfficeAllData = any;
  export const OfficeAllData: any;
  export type OrganizationSelectSearchModel = any;
  export const OrganizationSelectSearchModel: any;
  export type OrganizationSelectSearchType = any;
  export const OrganizationSelectSearchType: any;
  export type OutputFareConditionsPerBound = any;
  export const OutputFareConditionsPerBound: any;
  export type OutputFareConditionsPerBoundPerPtc = any;
  export const OutputFareConditionsPerBoundPerPtc: any;
  export type OutputFareConditionsPerPtc = any;
  export const OutputFareConditionsPerPtc: any;
  export type OutputFareConditionsPerPtcBounds = any;
  export const OutputFareConditionsPerPtcBounds: any;
  export type PassengerForServicingSeatmapScreen = any;
  export const PassengerForServicingSeatmapScreen: any;
  export type PassengerInformationRequestEditType = any;
  export const PassengerInformationRequestEditType: any;
  export type PassengerInformationRequestMastarData = any;
  export const PassengerInformationRequestMastarData: any;
  export type PassengerMailDestinationType = any;
  export const PassengerMailDestinationType: any;
  export type PassengerPhoneDestinationType = any;
  export const PassengerPhoneDestinationType: any;
  export type PassengerSecondContactType = any;
  export const PassengerSecondContactType: any;
  export type PassengerType = any;
  export const PassengerType: any;
  export type PhoneNumberType = any;
  export const PhoneNumberType: any;
  export type PlanListBoundReturn = any;
  export const PlanListBoundReturn: any;
  export type PlanListCurrentCart = any;
  export const PlanListCurrentCart: any;
  export type PlanListCurrentPlan = any;
  export const PlanListCurrentPlan: any;
  export type PlanListDiffFlg = any;
  export const PlanListDiffFlg: any;
  export type PlanListDiffInfo = any;
  export const PlanListDiffInfo: any;
  export type PlanListMAirportI18nList = any;
  export const PlanListMAirportI18nList: any;
  export type PlanListNumPerType = any;
  export const PlanListNumPerType: any;
  export type PlanListPassengerInfo = any;
  export const PlanListPassengerInfo: any;
  export type PlanListProcessType = any;
  export const PlanListProcessType: any;
  export type PlanListQueryParam = any;
  export const PlanListQueryParam: any;
  export type PlanListSegmentInfo = any;
  export const PlanListSegmentInfo: any;
  export type PlanListSelect = any;
  export const PlanListSelect: any;
  export type PlanReviewOutputBound = any;
  export const PlanReviewOutputBound: any;
  export type PlanReviewOutputFBagInfo = any;
  export const PlanReviewOutputFBagInfo: any;
  export type PlanReviewOutputFlight = any;
  export const PlanReviewOutputFlight: any;
  export type PlanReviewOutputFlightEndpoint = any;
  export const PlanReviewOutputFlightEndpoint: any;
  export type PlanReviewOutputFlightOutputCabinClass = any;
  export const PlanReviewOutputFlightOutputCabinClass: any;
  export type PlanReviewOutputLoungeInfo = any;
  export const PlanReviewOutputLoungeInfo: any;
  export type PlanReviewOutputMealInfo = any;
  export const PlanReviewOutputMealInfo: any;
  export type PlanReviewOutputPassengerInfosItem = any;
  export const PlanReviewOutputPassengerInfosItem: any;
  export type PlanReviewOutputPetInfo = any;
  export const PlanReviewOutputPetInfo: any;
  export type PlanReviewOutputPetInfoPassengerSegInfo = any;
  export const PlanReviewOutputPetInfoPassengerSegInfo: any;
  export type PlanReviewOutputRepContacts = any;
  export const PlanReviewOutputRepContacts: any;
  export type PlanReviewPlanHeaderAreaData = any;
  export const PlanReviewPlanHeaderAreaData: any;
  export type PlanReviewServiceDisplayState = any;
  export const PlanReviewServiceDisplayState: any;
  export type PlanSaveModalParams = any;
  export const PlanSaveModalParams: any;
  export type PreorderMealFlightAllData = any;
  export const PreorderMealFlightAllData: any;
  export type RamlContactsRepresentative = any;
  export const RamlContactsRepresentative: any;
  export type RamlContactsTraveler = any;
  export const RamlContactsTraveler: any;
  export type RamlFrequentFlyerCards = any;
  export const RamlFrequentFlyerCards: any;
  export type RamlServicesBaggage = any;
  export const RamlServicesBaggage: any;
  export type RamlServicesBaggageFirst = any;
  export const RamlServicesBaggageFirst: any;
  export type RamlServicesBaggageFirstSegment = any;
  export const RamlServicesBaggageFirstSegment: any;
  export type RamlServicesBaggageFirstSegmentMain = any;
  export const RamlServicesBaggageFirstSegmentMain: any;
  export type RamlServicesLounge = any;
  export const RamlServicesLounge: any;
  export type RamlServicesLoungeIdInfo = any;
  export const RamlServicesLoungeIdInfo: any;
  export type RamlServicesLoungeIdInfoMain = any;
  export const RamlServicesLoungeIdInfoMain: any;
  export type RamlServicesLoungeIdInfoMainCatalogue = any;
  export const RamlServicesLoungeIdInfoMainCatalogue: any;
  export type RamlServicesMeal = any;
  export const RamlServicesMeal: any;
  export type RamlServicesMealPassenger = any;
  export const RamlServicesMealPassenger: any;
  export type RamlServicesMealPassengerAppliedMeal = any;
  export const RamlServicesMealPassengerAppliedMeal: any;
  export type RangeValue = any;
  export const RangeValue: any;
  export type RegistrationLabelType = any;
  export const RegistrationLabelType: any;
  export type ReservationFunctionIdType = any;
  export const ReservationFunctionIdType: any;
  export type ReservationPageIdType = any;
  export const ReservationPageIdType: any;
  export type RoundtripFlightAvailabilityInternationalStoreModel = any;
  export const RoundtripFlightAvailabilityInternationalStoreModel: any;
  export type SeatForServicingSeatmapScreen = any;
  export const SeatForServicingSeatmapScreen: any;
  export type SeatForServicingSeatmapScreenBySegment = any;
  export const SeatForServicingSeatmapScreenBySegment: any;
  export type SeatInfo = any;
  export const SeatInfo: any;
  export type SeatInfoPassengers = any;
  export const SeatInfoPassengers: any;
  export type SeatmapStoreModel = any;
  export const SeatmapStoreModel: any;
  export type SelectCompanyAccountModel = any;
  export const SelectCompanyAccountModel: any;
  export type ServiceContentsByItineraryType = any;
  export const ServiceContentsByItineraryType: any;
  export type ServiceDescriptionsBySegment = any;
  export const ServiceDescriptionsBySegment: any;
  export type ShareholderCouponsType = any;
  export const ShareholderCouponsType: any;
  export type SupportInformationInputFoldingTypeModel = any;
  export const SupportInformationInputFoldingTypeModel: any;
  export type SupportInformationInputModel = any;
  export const SupportInformationInputModel: any;
  export type SupportInformationInputPregnantModel = any;
  export const SupportInformationInputPregnantModel: any;
  export type SupportInformationInputSpecialAssistanceModel = any;
  export const SupportInformationInputSpecialAssistanceModel: any;
  export type SupportInformationInputWalkingAbilityModel = any;
  export const SupportInformationInputWalkingAbilityModel: any;
  export type SupportInformationInputWheelchairTypeModel = any;
  export const SupportInformationInputWheelchairTypeModel: any;
  export type SupportInformationInputWheelchairsModel = any;
  export const SupportInformationInputWheelchairsModel: any;
  export type TaxAllLang = any;
  export const TaxAllLang: any;
  export type TaxAllLangItem = any;
  export const TaxAllLangItem: any;
  export type TempUrlType = any;
  export const TempUrlType: any;
  export type TemporaryUrlModalParams = any;
  export const TemporaryUrlModalParams: any;
  export type TravelerType = any;
  export const TravelerType: any;
  export type TripType = any;
  export const TripType: any;
  export type UpgradeInfoMap = any;
  export const UpgradeInfoMap: any;
  export type UpsellAirOffer = any;
  export const UpsellAirOffer: any;
  export type defaultGoshokaiNetLoginDynamicParams = any;
  export const defaultGoshokaiNetLoginDynamicParams: any;
  export type initialPassengerInformationRequestMastarData = any;
  export const initialPassengerInformationRequestMastarData: any;
}

declare module '@common/interfaces/common/m_bank_wellnet' {
  export type MBankWellnet = any;
  export const MBankWellnet: any;
}

declare module '@common/interfaces/master/m_payment_information' {
  export type MPaymentInformation = any;
  export const MPaymentInformation: any;
}

declare module '@common/services' {
  export type AddTravelersStoreService = any;
  export const AddTravelersStoreService: any;
  export type AnaBizLoginStoreService = any;
  export const AnaBizLoginStoreService: any;
  export type AnaBizLoginStoreServiceModule = any;
  export const AnaBizLoginStoreServiceModule: any;
  export type AnaBizLogoutStoreService = any;
  export const AnaBizLogoutStoreService: any;
  export type AnaBizTopService = any;
  export const AnaBizTopService: any;
  export type AnaBizTopServiceModule = any;
  export const AnaBizTopServiceModule: any;
  export type BookingCompletedSubHeaderInformationStoreService = any;
  export const BookingCompletedSubHeaderInformationStoreService: any;
  export type BookingCompletedSubHeaderInformationStoreServiceModule = any;
  export const BookingCompletedSubHeaderInformationStoreServiceModule: any;
  export type CancelPrebookService = any;
  export const CancelPrebookService: any;
  export type CancelPrebookServiceModule = any;
  export const CancelPrebookServiceModule: any;
  export type CartsUpdateServicesStoreServiceModule = any;
  export const CartsUpdateServicesStoreServiceModule: any;
  export type ComplexFlightAvailabilityPageStoreService = any;
  export const ComplexFlightAvailabilityPageStoreService: any;
  export type ComplexFlightCalendarStoreService = any;
  export const ComplexFlightCalendarStoreService: any;
  export type ComplexFlightCalendarStoreServiceModule = any;
  export const ComplexFlightCalendarStoreServiceModule: any;
  export type CreateCartStoreService = any;
  export const CreateCartStoreService: any;
  export type CreateCartStoreServiceModule = any;
  export const CreateCartStoreServiceModule: any;
  export type CreateOrderStoreService = any;
  export const CreateOrderStoreService: any;
  export type CreateOrderStoreServiceModule = any;
  export const CreateOrderStoreServiceModule: any;
  export type CreatePlansStoreService = any;
  export const CreatePlansStoreService: any;
  export type CreatePlansStoreServiceModule = any;
  export const CreatePlansStoreServiceModule: any;
  export type CriteoAlignmentService = any;
  export const CriteoAlignmentService: any;
  export type CriteoAlignmentServiceModule = any;
  export const CriteoAlignmentServiceModule: any;
  export type CurrentCartStoreService = any;
  export const CurrentCartStoreService: any;
  export type CurrentCartStoreServiceModule = any;
  export const CurrentCartStoreServiceModule: any;
  export type CurrentPlanStoreService = any;
  export const CurrentPlanStoreService: any;
  export type CurrentPlanStoreServiceModule = any;
  export const CurrentPlanStoreServiceModule: any;
  export type CurrentSeatmapService = any;
  export const CurrentSeatmapService: any;
  export type DcsDateService = any;
  export const DcsDateService: any;
  export type DcsDateServiceModule = any;
  export const DcsDateServiceModule: any;
  export type DeletePlansStoreService = any;
  export const DeletePlansStoreService: any;
  export type DeletePlansStoreServiceModule = any;
  export const DeletePlansStoreServiceModule: any;
  export type DeletePrebookedOrderStoreServiceModule = any;
  export const DeletePrebookedOrderStoreServiceModule: any;
  export type DeleteTravelerStoreService = any;
  export const DeleteTravelerStoreService: any;
  export type DeleteTravelerStoreServiceModule = any;
  export const DeleteTravelerStoreServiceModule: any;
  export type DeliveryInformationStoreService = any;
  export const DeliveryInformationStoreService: any;
  export type DeliveryInformationStoreServiceModule = any;
  export const DeliveryInformationStoreServiceModule: any;
  export type DiffEmphService = any;
  export const DiffEmphService: any;
  export type DiffEmphServiceModule = any;
  export const DiffEmphServiceModule: any;
  export type FareConditionsStoreService = any;
  export const FareConditionsStoreService: any;
  export type FareConditionsStoreServiceModule = any;
  export const FareConditionsStoreServiceModule: any;
  export type FindMoreFlightsStoreService = any;
  export const FindMoreFlightsStoreService: any;
  export type FindMoreFlightsStoreServiceModule = any;
  export const FindMoreFlightsStoreServiceModule: any;
  export type GetAirportListByCountryService = any;
  export const GetAirportListByCountryService: any;
  export type GetAirportListByCountryServiceModule = any;
  export const GetAirportListByCountryServiceModule: any;
  export type GetCartStoreService = any;
  export const GetCartStoreService: any;
  export type GetCartStoreServiceModule = any;
  export const GetCartStoreServiceModule: any;
  export type GetCompanyAccountsStoreService = any;
  export const GetCompanyAccountsStoreService: any;
  export type GetCompanyAccountsStoreServiceModule = any;
  export const GetCompanyAccountsStoreServiceModule: any;
  export type GetCreditPanInformationServiceModule = any;
  export const GetCreditPanInformationServiceModule: any;
  export type GetCreditPanInformationStoreService = any;
  export const GetCreditPanInformationStoreService: any;
  export type GetETicketItineraryReceiptStoreService = any;
  export const GetETicketItineraryReceiptStoreService: any;
  export type GetETicketItineraryReceiptStoreServiceModule = any;
  export const GetETicketItineraryReceiptStoreServiceModule: any;
  export type GetEstimationStoreService = any;
  export const GetEstimationStoreService: any;
  export type GetEstimationStoreServiceModule = any;
  export const GetEstimationStoreServiceModule: any;
  export type GetMealStoreService = any;
  export const GetMealStoreService: any;
  export type GetMealStoreServiceModule = any;
  export const GetMealStoreServiceModule: any;
  export type GetOrderStoreService = any;
  export const GetOrderStoreService: any;
  export type GetOrderStoreServiceModule = any;
  export const GetOrderStoreServiceModule: any;
  export type GetPlansStoreService = any;
  export const GetPlansStoreService: any;
  export type GetPlansStoreServiceModule = any;
  export const GetPlansStoreServiceModule: any;
  export type GetUnavailablePaymentByOfficeCodeService = any;
  export const GetUnavailablePaymentByOfficeCodeService: any;
  export type GetUnavailablePaymentByOfficeCodeServiceModule = any;
  export const GetUnavailablePaymentByOfficeCodeServiceModule: any;
  export type LocalDateService = any;
  export const LocalDateService: any;
  export type LocalDateServiceModule = any;
  export const LocalDateServiceModule: any;
  export type LocalPlanService = any;
  export const LocalPlanService: any;
  export type LocalPlanServiceModule = any;
  export const LocalPlanServiceModule: any;
  export type MemberAvailabilityStoreServiceModule = any;
  export const MemberAvailabilityStoreServiceModule: any;
  export type OrdersPaymentRecordsStoreService = any;
  export const OrdersPaymentRecordsStoreService: any;
  export type OrdersPaymentRecordsStoreServiceModule = any;
  export const OrdersPaymentRecordsStoreServiceModule: any;
  export type OrdersRepriceOrderStoreService = any;
  export const OrdersRepriceOrderStoreService: any;
  export type OrdersRepriceOrderStoreServiceModule = any;
  export const OrdersRepriceOrderStoreServiceModule: any;
  export type OrdersReservationAvailabilityStoreService = any;
  export const OrdersReservationAvailabilityStoreService: any;
  export type OrdersReservationAvailabilityStoreServiceModule = any;
  export const OrdersReservationAvailabilityStoreServiceModule: any;
  export type OrganizationSelectSearchStoreService = any;
  export const OrganizationSelectSearchStoreService: any;
  export type OrganizationSelectSearchStoreServiceModule = any;
  export const OrganizationSelectSearchStoreServiceModule: any;
  export type PasswordInputAuthLoginStoreServiceModule = any;
  export const PasswordInputAuthLoginStoreServiceModule: any;
  export type PaymentInputStoreService = any;
  export const PaymentInputStoreService: any;
  export type PaymentInputStoreServiceModule = any;
  export const PaymentInputStoreServiceModule: any;
  export type PetInputStoreService = any;
  export const PetInputStoreService: any;
  export type PetInputStoreServiceModule = any;
  export const PetInputStoreServiceModule: any;
  export type PlanListService = any;
  export const PlanListService: any;
  export type PlanListServiceModule = any;
  export const PlanListServiceModule: any;
  export type PlanListStoreService = any;
  export const PlanListStoreService: any;
  export type PlanListStoreServiceModule = any;
  export const PlanListStoreServiceModule: any;
  export type PlanReviewStoreService = any;
  export const PlanReviewStoreService: any;
  export type PlanReviewStoreServiceModule = any;
  export const PlanReviewStoreServiceModule: any;
  export type PlansCreatePlansStoreService = any;
  export const PlansCreatePlansStoreService: any;
  export type PlansCreatePlansStoreServiceModule = any;
  export const PlansCreatePlansStoreServiceModule: any;
  export type RefreshAmcmemberBalanceStoreService = any;
  export const RefreshAmcmemberBalanceStoreService: any;
  export type RefreshAmcmemberBalanceStoreServiceModule = any;
  export const RefreshAmcmemberBalanceStoreServiceModule: any;
  export type RoundtripOwdService = any;
  export const RoundtripOwdService: any;
  export type RoundtripOwdStoreServiceModule = any;
  export const RoundtripOwdStoreServiceModule: any;
  export type SearchFlightConditionForRequestService = any;
  export const SearchFlightConditionForRequestService: any;
  export type SearchFlightHistoryStoreService = any;
  export const SearchFlightHistoryStoreService: any;
  export type SearchFlightStoreService = any;
  export const SearchFlightStoreService: any;
  export type SearchFlightStoreServiceModule = any;
  export const SearchFlightStoreServiceModule: any;
  export type SelectCompanyAccountStoreService = any;
  export const SelectCompanyAccountStoreService: any;
  export type SelectCompanyAccountStoreServiceModule = any;
  export const SelectCompanyAccountStoreServiceModule: any;
  export type ShoppingLibService = any;
  export const ShoppingLibService: any;
  export type SupportInformationInputStoreService = any;
  export const SupportInformationInputStoreService: any;
  export type SupportInformationInputStoreServiceModule = any;
  export const SupportInformationInputStoreServiceModule: any;
  export type UpdateAirOffersStoreService = any;
  export const UpdateAirOffersStoreService: any;
  export type UpdateAirOffersStoreServiceModule = any;
  export const UpdateAirOffersStoreServiceModule: any;
  export type UpdatePlannameStoreService = any;
  export const UpdatePlannameStoreService: any;
  export type UpdatePlannameStoreServiceModule = any;
  export const UpdatePlannameStoreServiceModule: any;
  export type UpdateTravelersInformationStoreService = any;
  export const UpdateTravelersInformationStoreService: any;
  export type UpdateTravelersStoreServiceModule = any;
  export const UpdateTravelersStoreServiceModule: any;
  export type UpsellService = any;
  export const UpsellService: any;
  export type UpsellServiceModule = any;
  export const UpsellServiceModule: any;
}

declare module '@common/store' {
  export type AnaBizLoginState = any;
  export const AnaBizLoginState: any;
  export type AnaBizLoginStore = any;
  export const AnaBizLoginStore: any;
  export type AnaBizLoginStoreModule = any;
  export const AnaBizLoginStoreModule: any;
  export type AnaBizLogoutState = any;
  export const AnaBizLogoutState: any;
  export type AnaBizLogoutStore = any;
  export const AnaBizLogoutStore: any;
  export type AnaBizLogoutStoreModule = any;
  export const AnaBizLogoutStoreModule: any;
  export type BookingCompletedSubHeaderInformationStoreModule = any;
  export const BookingCompletedSubHeaderInformationStoreModule: any;
  export type Bound = any;
  export const Bound: any;
  export type ComplexFlightAvailabilityState = any;
  export const ComplexFlightAvailabilityState: any;
  export type ComplexFlightAvailabilityStore = any;
  export const ComplexFlightAvailabilityStore: any;
  export type ComplexFlightAvailabilityStoreModule = any;
  export const ComplexFlightAvailabilityStoreModule: any;
  export type ComplexFlightCalendarState = any;
  export const ComplexFlightCalendarState: any;
  export type ComplexFlightCalendarStore = any;
  export const ComplexFlightCalendarStore: any;
  export type CreateCartStore = any;
  export const CreateCartStore: any;
  export type CreateOrderState = any;
  export const CreateOrderState: any;
  export type CreateOrderStoreModule = any;
  export const CreateOrderStoreModule: any;
  export type CreatePlansState = any;
  export const CreatePlansState: any;
  export type CurrentCartModel = any;
  export const CurrentCartModel: any;
  export type CurrentCartState = any;
  export const CurrentCartState: any;
  export type CurrentCartStoreModule = any;
  export const CurrentCartStoreModule: any;
  export type CurrentPlanModel = any;
  export const CurrentPlanModel: any;
  export type CurrentPlanState = any;
  export const CurrentPlanState: any;
  export type CurrentPlanStoreModule = any;
  export const CurrentPlanStoreModule: any;
  export type CurrentSeatmapState = any;
  export const CurrentSeatmapState: any;
  export type CurrentSeatmapStore = any;
  export const CurrentSeatmapStore: any;
  export type CurrentSeatmapStoreModule = any;
  export const CurrentSeatmapStoreModule: any;
  export type DeletePrebookedOrderStoreModule = any;
  export const DeletePrebookedOrderStoreModule: any;
  export type DeliveryInformationState = any;
  export const DeliveryInformationState: any;
  export type DeliveryInformationStoreModule = any;
  export const DeliveryInformationStoreModule: any;
  export type FareConditionsState = any;
  export const FareConditionsState: any;
  export type FareConditionsStoreModule = any;
  export const FareConditionsStoreModule: any;
  export type FindMoreFlightsPostStoreModule = any;
  export const FindMoreFlightsPostStoreModule: any;
  export type FindMoreFlightsState = any;
  export const FindMoreFlightsState: any;
  export type FindMoreFlightsStore = any;
  export const FindMoreFlightsStore: any;
  export type FindMoreFlightsStoreModule = any;
  export const FindMoreFlightsStoreModule: any;
  export type GetCartState = any;
  export const GetCartState: any;
  export type GetCartStoreModule = any;
  export const GetCartStoreModule: any;
  export type GetCompanyAccountsState = any;
  export const GetCompanyAccountsState: any;
  export type GetCompanyAccountsStore = any;
  export const GetCompanyAccountsStore: any;
  export type GetCompanyAccountsStoreModule = any;
  export const GetCompanyAccountsStoreModule: any;
  export type GetCreditPanInformationState = any;
  export const GetCreditPanInformationState: any;
  export type GetCreditPanInformationStore = any;
  export const GetCreditPanInformationStore: any;
  export type GetCreditPanInformationStoreModule = any;
  export const GetCreditPanInformationStoreModule: any;
  export type GetETicketItineraryReceiptStoreModule = any;
  export const GetETicketItineraryReceiptStoreModule: any;
  export type GetMealState = any;
  export const GetMealState: any;
  export type GetOrderState = any;
  export const GetOrderState: any;
  export type GetOrderStoreModule = any;
  export const GetOrderStoreModule: any;
  export type GetPlansState = any;
  export const GetPlansState: any;
  export type GetPlansStoreModule = any;
  export const GetPlansStoreModule: any;
  export type MemberAvailabilityStoreModule = any;
  export const MemberAvailabilityStoreModule: any;
  export type OrdersPaymentRecordsState = any;
  export const OrdersPaymentRecordsState: any;
  export type OrdersRepriceOrderState = any;
  export const OrdersRepriceOrderState: any;
  export type OrdersReservationAvailabilityStoreModule = any;
  export const OrdersReservationAvailabilityStoreModule: any;
  export type OrganizationSelectSearchState = any;
  export const OrganizationSelectSearchState: any;
  export type OrganizationSelectSearchStore = any;
  export const OrganizationSelectSearchStore: any;
  export type OrganizationSelectSearchStoreModule = any;
  export const OrganizationSelectSearchStoreModule: any;
  export type PaymentInputState = any;
  export const PaymentInputState: any;
  export type PetInputState = any;
  export const PetInputState: any;
  export type PetInputStoreModule = any;
  export const PetInputStoreModule: any;
  export type PlanListModel = any;
  export const PlanListModel: any;
  export type PlanListStoreModule = any;
  export const PlanListStoreModule: any;
  export type PlanReviewStoreModule = any;
  export const PlanReviewStoreModule: any;
  export type RefreshAmcmemberBalanceState = any;
  export const RefreshAmcmemberBalanceState: any;
  export type RoundTrip = any;
  export const RoundTrip: any;
  export type SearchFlightConditionForRequest = any;
  export const SearchFlightConditionForRequest: any;
  export type SearchFlightConditionForRequestState = any;
  export const SearchFlightConditionForRequestState: any;
  export type SearchFlightConstant = any;
  export const SearchFlightConstant: any;
  export type SearchFlightState = any;
  export const SearchFlightState: any;
  export type SearchFlightStateDetails = any;
  export const SearchFlightStateDetails: any;
  export type SeatmapsState = any;
  export const SeatmapsState: any;
  export type SeatmapsStoreModule = any;
  export const SeatmapsStoreModule: any;
  export type SelectCompanyAccountState = any;
  export const SelectCompanyAccountState: any;
  export type SelectCompanyAccountStore = any;
  export const SelectCompanyAccountStore: any;
  export type SelectCompanyAccountStoreModule = any;
  export const SelectCompanyAccountStoreModule: any;
  export type SupportInformationInputState = any;
  export const SupportInformationInputState: any;
  export type TripType = any;
  export const TripType: any;
  export type UpdateTravelersState = any;
  export const UpdateTravelersState: any;
  export type UpdateTravelersStoreModule = any;
  export const UpdateTravelersStoreModule: any;
  export type UpsellFunctionType = any;
  export const UpsellFunctionType: any;
  export type ordersReservationAvailabilityInitialState = any;
  export const ordersReservationAvailabilityInitialState: any;
  export type resetAnaBizLogin = any;
  export const resetAnaBizLogin: any;
  export type resetAnaBizLogout = any;
  export const resetAnaBizLogout: any;
  export type resetComplexFlightAvailability = any;
  export const resetComplexFlightAvailability: any;
  export type resetComplexFlightCalendar = any;
  export const resetComplexFlightCalendar: any;
  export type resetCurrentSeatmap = any;
  export const resetCurrentSeatmap: any;
  export type resetFindMoreFlights = any;
  export const resetFindMoreFlights: any;
  export type resetGetCompanyAccounts = any;
  export const resetGetCompanyAccounts: any;
  export type resetOrganizationSelectSearch = any;
  export const resetOrganizationSelectSearch: any;
  export type resetSelectCompanyAccount = any;
  export const resetSelectCompanyAccount: any;
  export type searchFlightInitialState = any;
  export const searchFlightInitialState: any;
  export type selectAnaBizLoginState = any;
  export const selectAnaBizLoginState: any;
  export type selectAnaBizLogoutState = any;
  export const selectAnaBizLogoutState: any;
  export type selectComplexFlightAvailabilityState = any;
  export const selectComplexFlightAvailabilityState: any;
  export type selectComplexFlightCalendarState = any;
  export const selectComplexFlightCalendarState: any;
  export type selectCreateCartIsFailureStatus = any;
  export const selectCreateCartIsFailureStatus: any;
  export type selectCurrentSeatmapState = any;
  export const selectCurrentSeatmapState: any;
  export type selectFindMoreFlightsState = any;
  export const selectFindMoreFlightsState: any;
  export type selectGetCompanyAccountsState = any;
  export const selectGetCompanyAccountsState: any;
  export type selectGetCreditPanInformationState = any;
  export const selectGetCreditPanInformationState: any;
  export type selectOrganizationSelectSearchState = any;
  export const selectOrganizationSelectSearchState: any;
  export type selectSelectCompanyAccountState = any;
  export const selectSelectCompanyAccountState: any;
  export type setAnaBizLogin = any;
  export const setAnaBizLogin: any;
  export type setAnaBizLoginFromApi = any;
  export const setAnaBizLoginFromApi: any;
  export type setAnaBizLogoutFromApi = any;
  export const setAnaBizLogoutFromApi: any;
  export type setComplexFlightAvailability = any;
  export const setComplexFlightAvailability: any;
  export type setComplexFlightCalendar = any;
  export const setComplexFlightCalendar: any;
  export type setCurrentSeatmap = any;
  export const setCurrentSeatmap: any;
  export type setFindMoreFlights = any;
  export const setFindMoreFlights: any;
  export type setGetCompanyAccountsFromApi = any;
  export const setGetCompanyAccountsFromApi: any;
  export type setGetCreditPanInformationFromApi = any;
  export const setGetCreditPanInformationFromApi: any;
  export type setOrganizationSelectSearch = any;
  export const setOrganizationSelectSearch: any;
  export type setSelectCompanyAccountFromApi = any;
  export const setSelectCompanyAccountFromApi: any;
  export type updateAnaBizLogin = any;
  export const updateAnaBizLogin: any;
  export type updateComplexFlightAvailability = any;
  export const updateComplexFlightAvailability: any;
  export type updateComplexFlightCalendar = any;
  export const updateComplexFlightCalendar: any;
  export type updateCurrentSeatmap = any;
  export const updateCurrentSeatmap: any;
  export type updateFindMoreFlights = any;
  export const updateFindMoreFlights: any;
  export type updateOrganizationSelectSearch = any;
  export const updateOrganizationSelectSearch: any;
}

declare module '@lib/helpers' {
  export type AswValidators = any;
  export const AswValidators: any;
  export type convertEmailAddress = any;
  export const convertEmailAddress: any;
  export type convertPaxName = any;
  export const convertPaxName: any;
  export type convertPhoneNumber = any;
  export const convertPhoneNumber: any;
  export type convertReservationInfo = any;
  export const convertReservationInfo: any;
  export type convertSpaceNormalize = any;
  export const convertSpaceNormalize: any;
  export type convertStringToDate = any;
  export const convertStringToDate: any;
  export type convertToHyphen = any;
  export const convertToHyphen: any;
  export type isAlphaNumeric = any;
  export const isAlphaNumeric: any;
  export type isNumeric = any;
  export const isNumeric: any;
  export type isPC = any;
  export const isPC: any;
  export type isSP = any;
  export const isSP: any;
  export type isTB = any;
  export const isTB: any;
  export type isVisible = any;
  export const isVisible: any;
  export type matchedRegexPattern = any;
  export const matchedRegexPattern: any;
  export type uniqueId = any;
  export const uniqueId: any;
}

declare module '@lib/interfaces' {
  export type AMCMemberModel = any;
  export const AMCMemberModel: any;
  export type AMCMemberType = any;
  export const AMCMemberType: any;
  export type Airport = any;
  export const Airport: any;
  export type AlertMessageItem = any;
  export const AlertMessageItem: any;
  export type AlertType = any;
  export const AlertType: any;
  export type AnaBizContextModel = any;
  export const AnaBizContextModel: any;
  export type AnaBizLoginStatusType = any;
  export const AnaBizLoginStatusType: any;
  export type AnaCardTypeCodeType = any;
  export const AnaCardTypeCodeType: any;
  export type ApiCommonRequest = any;
  export const ApiCommonRequest: any;
  export type ApiErrorResponseModel = any;
  export const ApiErrorResponseModel: any;
  export type AswCommonType = any;
  export const AswCommonType: any;
  export type AswContextModel = any;
  export const AswContextModel: any;
  export type AswContextType = any;
  export const AswContextType: any;
  export type AswServiceModel = any;
  export const AswServiceModel: any;
  export type BookingType = any;
  export const BookingType: any;
  export type CamelToSnake = any;
  export const CamelToSnake: any;
  export type DeviceType = any;
  export const DeviceType: any;
  export type DialogClickType = any;
  export const DialogClickType: any;
  export type DialogInfo = any;
  export const DialogInfo: any;
  export type DialogSize = any;
  export const DialogSize: any;
  export type DialogType = any;
  export const DialogType: any;
  export type DynamicContent = any;
  export const DynamicContent: any;
  export type DynamicContentType = any;
  export const DynamicContentType: any;
  export type DynamicParams = any;
  export const DynamicParams: any;
  export type ErrorPageRoutes = any;
  export const ErrorPageRoutes: any;
  export type ErrorType = any;
  export const ErrorType: any;
  export type GenderCodeType = any;
  export const GenderCodeType: any;
  export type I18nConfig = any;
  export const I18nConfig: any;
  export type IFlyAddressType = any;
  export const IFlyAddressType: any;
  export type IFlyGenderType = any;
  export const IFlyGenderType: any;
  export type IFlyPhoneNumberType = any;
  export const IFlyPhoneNumberType: any;
  export type LoadAswMasterInfo = any;
  export const LoadAswMasterInfo: any;
  export type LoadingDisplayMode = any;
  export const LoadingDisplayMode: any;
  export type LogType = any;
  export const LogType: any;
  export type LoginStatusType = any;
  export const LoginStatusType: any;
  export type MOffice = any;
  export const MOffice: any;
  export type MemberKindCodeType = any;
  export const MemberKindCodeType: any;
  export type NotRetryableErrorModel = any;
  export const NotRetryableErrorModel: any;
  export type PageIdType = any;
  export const PageIdType: any;
  export type PageType = any;
  export const PageType: any;
  export type PremiumStatusCodeType = any;
  export const PremiumStatusCodeType: any;
  export type ReplaceParam = any;
  export const ReplaceParam: any;
  export type RetryableError = any;
  export const RetryableError: any;
  export type SessionStorageName = any;
  export const SessionStorageName: any;
  export type SnakeToCamelCase = any;
  export const SnakeToCamelCase: any;
  export type TealiumDataKey = any;
  export const TealiumDataKey: any;
  export type TealiumMode = any;
  export const TealiumMode: any;
  export type ValidateLengthOptions = any;
  export const ValidateLengthOptions: any;
  export type ValidateNumericRangeOptions = any;
  export const ValidateNumericRangeOptions: any;
  export type ValidateOptions = any;
  export const ValidateOptions: any;
  export type ValidatePhoneNumberOptions = any;
  export const ValidatePhoneNumberOptions: any;
  export type ValidateRequiredOptions = any;
  export const ValidateRequiredOptions: any;
  export type ValidationErrorInfo = any;
  export const ValidationErrorInfo: any;
  export type breakpointSp = any;
  export const breakpointSp: any;
}

declare module '@lib/pipes' {
  export type AmountFormatModule = any;
  export const AmountFormatModule: any;
  export type AmountFormatPipe = any;
  export const AmountFormatPipe: any;
  export type DateFormatModule = any;
  export const DateFormatModule: any;
  export type DateFormatPipe = any;
  export const DateFormatPipe: any;
  export type HeaderUrlModule = any;
  export const HeaderUrlModule: any;
  export type HeaderUrlPipe = any;
  export const HeaderUrlPipe: any;
  export type LinkStylePipeModule = any;
  export const LinkStylePipeModule: any;
  export type LinkUrlModule = any;
  export const LinkUrlModule: any;
  export type LinkUrlPipe = any;
  export const LinkUrlPipe: any;
  export type MetaUrlModule = any;
  export const MetaUrlModule: any;
  export type NumberFormatModule = any;
  export const NumberFormatModule: any;
  export type ParamsTranslateModule = any;
  export const ParamsTranslateModule: any;
  export type PopupIndicatorPipeModule = any;
  export const PopupIndicatorPipeModule: any;
  export type StaticMsgModule = any;
  export const StaticMsgModule: any;
  export type StaticMsgPipe = any;
  export const StaticMsgPipe: any;
}

declare module '@lib/services' {
  export type AMCMemberStoreService = any;
  export const AMCMemberStoreService: any;
  export type AlertMessageStoreService = any;
  export const AlertMessageStoreService: any;
  export type AnaBizContextStoreService = any;
  export const AnaBizContextStoreService: any;
  export type ApiErrorResponseService = any;
  export const ApiErrorResponseService: any;
  export type AswCommonStoreService = any;
  export const AswCommonStoreService: any;
  export type AswContextStoreService = any;
  export const AswContextStoreService: any;
  export type AswMasterService = any;
  export const AswMasterService: any;
  export type AswMissingTranslationHandler = any;
  export const AswMissingTranslationHandler: any;
  export type AswServiceStoreService = any;
  export const AswServiceStoreService: any;
  export type AuthorizationService = any;
  export const AuthorizationService: any;
  export type AuthorizationServiceModule = any;
  export const AuthorizationServiceModule: any;
  export type CommonLibModule = any;
  export const CommonLibModule: any;
  export type CommonLibService = any;
  export const CommonLibService: any;
  export type DataDogCustomConfig = any;
  export const DataDogCustomConfig: any;
  export type DialogDisplayService = any;
  export const DialogDisplayService: any;
  export type DialogDisplayServiceModule = any;
  export const DialogDisplayServiceModule: any;
  export type DynamicContentService = any;
  export const DynamicContentService: any;
  export type ErrorsHandlerService = any;
  export const ErrorsHandlerService: any;
  export type GetAwardUsersStoreService = any;
  export const GetAwardUsersStoreService: any;
  export type GetAwardUsersStoreServiceModule = any;
  export const GetAwardUsersStoreServiceModule: any;
  export type GetMemberInformationStoreService = any;
  export const GetMemberInformationStoreService: any;
  export type GetMemberInformationStoreServiceModule = any;
  export const GetMemberInformationStoreServiceModule: any;
  export type HeaderService = any;
  export const HeaderService: any;
  export type HeaderServiceModule = any;
  export const HeaderServiceModule: any;
  export type InitialInfluxService = any;
  export const InitialInfluxService: any;
  export type InitialInfluxServiceModule = any;
  export const InitialInfluxServiceModule: any;
  export type LoadScriptService = any;
  export const LoadScriptService: any;
  export type LoggerDatadogService = any;
  export const LoggerDatadogService: any;
  export type LoggerDatadogServiceModule = any;
  export const LoggerDatadogServiceModule: any;
  export type LoginInfoStoreServiceModule = any;
  export const LoginInfoStoreServiceModule: any;
  export type ModalBlockParts = any;
  export const ModalBlockParts: any;
  export type ModalIdParts = any;
  export const ModalIdParts: any;
  export type ModalService = any;
  export const ModalService: any;
  export type ModalServiceModule = any;
  export const ModalServiceModule: any;
  export type PageInitService = any;
  export const PageInitService: any;
  export type PageLoadingService = any;
  export const PageLoadingService: any;
  export type RESTRICTED_NAVIGATION_INITIALIZER_PROVIDER = any;
  export const RESTRICTED_NAVIGATION_INITIALIZER_PROVIDER: any;
  export type SystemDateService = any;
  export const SystemDateService: any;
  export type TealiumService = any;
  export const TealiumService: any;
}

declare module '@lib/store' {
  export type AMCMemberState = any;
  export const AMCMemberState: any;
  export type AMCMemberStore = any;
  export const AMCMemberStore: any;
  export type AMCMemberStoreModule = any;
  export const AMCMemberStoreModule: any;
  export type AnaBizContextStoreModule = any;
  export const AnaBizContextStoreModule: any;
  export type ApiErrorResponseStoreModule = any;
  export const ApiErrorResponseStoreModule: any;
  export type AswCommonState = any;
  export const AswCommonState: any;
  export type AswCommonStoreModule = any;
  export const AswCommonStoreModule: any;
  export type AswContextState = any;
  export const AswContextState: any;
  export type AswContextStoreModule = any;
  export const AswContextStoreModule: any;
  export type AswMasterStoreModule = any;
  export const AswMasterStoreModule: any;
  export type AswServiceStoreModule = any;
  export const AswServiceStoreModule: any;
  export type AsyncRequest = any;
  export const AsyncRequest: any;
  export type AsyncStoreItem = any;
  export const AsyncStoreItem: any;
  export type AuthLoginState = any;
  export const AuthLoginState: any;
  export type AuthLoginStore = any;
  export const AuthLoginStore: any;
  export type DynamicContentStoreModule = any;
  export const DynamicContentStoreModule: any;
  export type FromApiActionPayload = any;
  export const FromApiActionPayload: any;
  export type GetAwardUsersState = any;
  export const GetAwardUsersState: any;
  export type GetAwardUsersStore = any;
  export const GetAwardUsersStore: any;
  export type GetEncryptedLoginInfoStoreModule = any;
  export const GetEncryptedLoginInfoStoreModule: any;
  export type GetMemberInformationState = any;
  export const GetMemberInformationState: any;
  export type GetMemberInformationStore = any;
  export const GetMemberInformationStore: any;
  export type GetMemberInformationStoreModule = any;
  export const GetMemberInformationStoreModule: any;
  export type NotRetryableErrorStoreModule = any;
  export const NotRetryableErrorStoreModule: any;
  export type PageLoadingStore = any;
  export const PageLoadingStore: any;
  export type PageLoadingStoreModule = any;
  export const PageLoadingStoreModule: any;
  export type RetryableErrorStoreModule = any;
  export const RetryableErrorStoreModule: any;
  export type SysdateStoreModule = any;
  export const SysdateStoreModule: any;
  export type WithRequestId = any;
  export const WithRequestId: any;
  export type asyncProps = any;
  export const asyncProps: any;
  export type asyncStoreItemAdapter = any;
  export const asyncStoreItemAdapter: any;
  export type fromApiEffectSwitchMap = any;
  export const fromApiEffectSwitchMap: any;
  export type resetAMCMember = any;
  export const resetAMCMember: any;
  export type resetGetMemberInformation = any;
  export const resetGetMemberInformation: any;
  export type selectAMCMemberState = any;
  export const selectAMCMemberState: any;
  export type selectAuthLoginState = any;
  export const selectAuthLoginState: any;
  export type selectGetMemberInformationState = any;
  export const selectGetMemberInformationState: any;
  export type selectPageLoadingState = any;
  export const selectPageLoadingState: any;
  export type setAMCMember = any;
  export const setAMCMember: any;
  export type setAuthLoginFromApi = any;
  export const setAuthLoginFromApi: any;
  export type setGetAwardUsersFromApi = any;
  export const setGetAwardUsersFromApi: any;
  export type setGetMemberInformationFromApi = any;
  export const setGetMemberInformationFromApi: any;
  export type storeSyncMetaReducer = any;
  export const storeSyncMetaReducer: any;
  export type updateAMCMember = any;
  export const updateAMCMember: any;
  export type updatePageLoading = any;
  export const updatePageLoading: any;
}

declare module 'src/sdk-amcmember/model/getAwardUsersResponseDataAwardUsersInner' {
  export type GetAwardUsersResponseDataAwardUsersInner = any;
  export const GetAwardUsersResponseDataAwardUsersInner: any;
}

declare module 'src/sdk-credit' {
  export type ApiCreditModule = any;
  export const ApiCreditModule: any;
  export type Configuration = any;
  export const Configuration: any;
  export type CreditApiService = any;
  export const CreditApiService: any;
  export type GetCreditPanInformationResponse = any;
  export const GetCreditPanInformationResponse: any;
  export type GetCreditPanInformationResponseData = any;
  export const GetCreditPanInformationResponseData: any;
}

declare module 'src/sdk-member' {
  export type ApiMemberModule = any;
  export const ApiMemberModule: any;
  export type AuthLoginRequest = any;
  export const AuthLoginRequest: any;
  export type AuthLoginResponse = any;
  export const AuthLoginResponse: any;
  export type Configuration = any;
  export const Configuration: any;
  export type GetMemberInformationResponse = any;
  export const GetMemberInformationResponse: any;
  export type MemberApiService = any;
  export const MemberApiService: any;
  export type MemberAvailabilityRequest = any;
  export const MemberAvailabilityRequest: any;
  export type MemberAvailabilityResponse = any;
  export const MemberAvailabilityResponse: any;
  export type ReservationAvailabilityRequest = any;
  export const ReservationAvailabilityRequest: any;
  export type ReservationAvailabilityResponse = any;
  export const ReservationAvailabilityResponse: any;
}

declare module 'src/sdk-servicing' {
  export type ApiServicingModule = any;
  export const ApiServicingModule: any;
  export type Bound = any;
  export const Bound: any;
  export type Configuration = any;
  export const Configuration: any;
  export type CreateMycarValetResponseWarningsInner = any;
  export const CreateMycarValetResponseWarningsInner: any;
  export type FareConditionsRequest = any;
  export const FareConditionsRequest: any;
  export type FareConditionsResponse = any;
  export const FareConditionsResponse: any;
  export type FareConditionsResponseData = any;
  export const FareConditionsResponseData: any;
  export type FareConditionsResponseDataAirOfferConditions = any;
  export const FareConditionsResponseDataAirOfferConditions: any;
  export type FareConditionsResponseDataAirOfferConditionsPtc = any;
  export const FareConditionsResponseDataAirOfferConditionsPtc: any;
  export type GetETicketItineraryReceiptRequest = any;
  export const GetETicketItineraryReceiptRequest: any;
  export type GetETicketItineraryReceiptResponse = any;
  export const GetETicketItineraryReceiptResponse: any;
  export type GetEmdPassengerReceiptRequest = any;
  export const GetEmdPassengerReceiptRequest: any;
  export type GetMealRequest = any;
  export const GetMealRequest: any;
  export type GetMealResponse = any;
  export const GetMealResponse: any;
  export type GetMealResponseDataDD = any;
  export const GetMealResponseDataDD: any;
  export type GetMealResponseDataDDChargeableMealListInner = any;
  export const GetMealResponseDataDDChargeableMealListInner: any;
  export type GetMealResponseDataDDPreorderMealListInner = any;
  export const GetMealResponseDataDDPreorderMealListInner: any;
  export type GetOrderRequest = any;
  export const GetOrderRequest: any;
  export type GetOrderResponse = any;
  export const GetOrderResponse: any;
  export type GetOrderResponseData = any;
  export const GetOrderResponseData: any;
  export type GetOrderResponseDataAir = any;
  export const GetOrderResponseDataAir: any;
  export type GetOrderResponseDataNextActionsOfflinePaymentDetails = any;
  export const GetOrderResponseDataNextActionsOfflinePaymentDetails: any;
  export type GetOrderResponseDataOrderEligibilitiesPayment = any;
  export const GetOrderResponseDataOrderEligibilitiesPayment: any;
  export type GetOrderResponseDataOrderType = any;
  export const GetOrderResponseDataOrderType: any;
  export type GetOrderResponseDataServiceSummaryHasRequested = any;
  export const GetOrderResponseDataServiceSummaryHasRequested: any;
  export type GetOrderResponseDataServicesBaggageItem = any;
  export const GetOrderResponseDataServicesBaggageItem: any;
  export type GetOrderResponseDataTravelDocumentsInner = any;
  export const GetOrderResponseDataTravelDocumentsInner: any;
  export type GetOrderResponseDataTravelersSummaryTravelerNumbers = any;
  export const GetOrderResponseDataTravelersSummaryTravelerNumbers: any;
  export type GetSeatmapsRequest = any;
  export const GetSeatmapsRequest: any;
  export type GetSeatmapsResponse = any;
  export const GetSeatmapsResponse: any;
  export type GetSeatmapsResponseDataSeatmapsDecksInner = any;
  export const GetSeatmapsResponseDataSeatmapsDecksInner: any;
  export type GetSeatmapsResponseDataSeatmapsDecksInnerSeatsInnerRowsInner = any;
  export const GetSeatmapsResponseDataSeatmapsDecksInnerSeatsInnerRowsInner: any;
  export type GetSeatmapsResponseDataSeatmapsDecksInnerSeatsInnerRowsInnerColumnsInner = any;
  export const GetSeatmapsResponseDataSeatmapsDecksInnerSeatsInnerRowsInnerColumnsInner: any;
  export type GetSeatmapsResponseDataSeatmapsDecksInnerSeatsRowsInnerRowFacilities = any;
  export const GetSeatmapsResponseDataSeatmapsDecksInnerSeatsRowsInnerRowFacilities: any;
  export type OrderSeatItem = any;
  export const OrderSeatItem: any;
  export type OrderSeatItemSeatSelection = any;
  export const OrderSeatItemSeatSelection: any;
  export type PaymentRequestAlternativePaymentMethod = any;
  export const PaymentRequestAlternativePaymentMethod: any;
  export type PetRakunoriResponse = any;
  export const PetRakunoriResponse: any;
  export type ServicingApiService = any;
  export const ServicingApiService: any;
  export type Traveler = any;
  export const Traveler: any;
  export type TravelerNamesInner = any;
  export const TravelerNamesInner: any;
  export type Type1 = any;
  export const Type1: any;
  export type TypeErrorsInnerSource = any;
  export const TypeErrorsInnerSource: any;
  export type UpdateServicesRequest = any;
  export const UpdateServicesRequest: any;
  export type UpdateServicesRequestSeatsChildSeatsInner = any;
  export const UpdateServicesRequestSeatsChildSeatsInner: any;
  export type UpdateServicesRequestSeatsSeatReservationInner = any;
  export const UpdateServicesRequestSeatsSeatReservationInner: any;
  export type UpdateServicesRequestServicesInner = any;
  export const UpdateServicesRequestServicesInner: any;
  export type UpdateServicesRequestServicesInnerSegmentsInner = any;
  export const UpdateServicesRequestServicesInnerSegmentsInner: any;
  export type UpdateServicesResponse = any;
  export const UpdateServicesResponse: any;
}

